apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore-service
spec:
  ports:
  - port: 80
    name: web-app
    protocol: TCP
    targetPort: 5000
  selector:
    app: bookstore
  type: LoadBalancer