apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-workbench
  name: mysql-workbench-service
spec:
  ports:
  - port: 80
    name: mysql-workbench
    protocol: TCP
    targetPort: 3000
  selector:
    app: mysql-workbench
  type: LoadBalancer