apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: bookstore
  POSTGRES_USER: hieuut
  POSTGRES_PASSWORD: hieuut
  PGDATA: /var/lib/postgresql/data/pgdata