apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin4
  name: pgadmin4-service
spec:
  ports:
  - port: 80
    name: pgadmin4
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin4
  type: LoadBalancer